apiVersion: v1
kind: Service
metadata:
  name: basic-webserver
spec:
  selector:
    app: basic-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort